version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: crypto-rabbit
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  redis:
    image: redis:7-alpine
    container_name: crypto-redis
    ports:
      - '6379:6379'

  app:
    build: .
    container_name: crypto-exchange-app
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    ports:
      - "3000:3000"
